# -*- coding: utf-8 -*-
"""Multi-pdf ChatApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2UdjSd2XQc-xXqP05ucY1Q95DYF5co9
"""

!pip install -U langchain langchain-community langchain-text-splitters chromadb sentence-transformers


from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

texts = text_splitter.split_documents(documents)

print("Total chunks:", len(texts))

from langchain_community.document_loaders import PyPDFLoader
import os

documents = []

pdf_files = [f for f in os.listdir("/content") if f.endswith(".pdf")]

print("PDFs found:", pdf_files)

for file in pdf_files:
    loader = PyPDFLoader(os.path.join("/content", file))
    documents.extend(loader.load())

print("Total pages loaded:", len(documents))


from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)
vectorstore = Chroma.from_documents(
    texts,   # your split documents
    embedding=embeddings
)

print("Vectorstore created successfully 🚀")

!pip install -U sentence-transformers

!pip install -U langchain langchain-community chromadb sentence-transformers


print(results[0].page_content)